<?php

namespace AppBundle\Repository;

/**
 * InternationalOrgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternationalOrgRepository extends \Doctrine\ORM\EntityRepository
{
}
