<?php

namespace AppBundle\Repository;

/**
 * IntOrgMembershipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntOrgMembershipRepository extends \Doctrine\ORM\EntityRepository
{
}
