<?php

namespace AppBundle\Repository;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatisticRepository extends \Doctrine\ORM\EntityRepository
{
}
